# Generated by Django 2.2.3 on 2019-07-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20190721_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/<django.db.models.query_utils.DeferredAttribute object at 0x0000007A362E0438>/'),
        ),
    ]
