# Generated by Django 2.2.3 on 2019-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190721_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/<django.db.models.query_utils.DeferredAttribute object at 0x000000592D72EEB8>/'),
        ),
    ]
